### ISSUE TITLE
Blockers for the update to V8 8.0

### ISSUE THREAD

**Issue by targos** [nodejs/node-v8#127]
We've got quite a few things to fix this time!

- [ ] [Failing test-inspector-multisession-ws](https://github.com/nodejs/node-v8/issues/120)
- [x] [Failing test-assert](https://github.com/nodejs/node-v8/issues/122)
- [x] [S390x fails to build](https://github.com/nodejs/node-v8/issues/123)
- [x] [FreeBSD fails to build](https://github.com/nodejs/node-v8/issues/124)
- [x] [SmartOS fails to build](https://github.com/nodejs/node-v8/issues/125)
- [x] [Windows fails to build (VS2019)](https://github.com/nodejs/node-v8/issues/126)
- [x] [Windows fails to build (VS2017)](https://github.com/nodejs/node-v8/issues/128)
- [x] [Broken debug build](https://github.com/nodejs/node-v8/issues/129)
- [x] [incomplete zlib.gyp](https://github.com/nodejs/node-v8/issues/130)
- [x] [V8 zlib target fails for cross-compilation](https://github.com/nodejs/node-v8/issues/137)
- [x] [Debug build not working without `--experimental-enable-pointer-compression`](https://github.com/nodejs/node-v8/issues/140)

**Comment by bnoordhuis** [comment]
@targos Does https://github.com/nodejs/node-v8/issues/130#issuecomment-562848278 mean that the "incomplete zlib.gyp" bullet point should be checked off?

**Comment by targos** [comment]
@bnoordhuis I suppose we can check it off because it's no longer a blocker, but I didn't implement the conditions to load optimized code depending on the platform.

**Comment by Zaseth** [comment]
Is this still being worked on? I would love to have the latest v8.

**Comment by gengjiawen** [comment]
> Is this still being worked on? I would love to have the latest v8.

Yeap. We have just fixed build issue on vs2019. Still some work todo. See https://github.com/nodejs/node-v8/issues/127#issue-532724601 for update.

**Comment by SFx2018** [comment]
any news? :D looking forward for it :D

**Comment by addaleax** [comment]
@SFx2018 There is a checklist at the top of this PR :)

**Comment by hashseed** [comment]
V8 had to make some changes to make building with zlib work again: https://chromium-review.googlesource.com/c/v8/node-ci/+/2037570

**Comment by SFx2018** [comment]
any ETA for release for nodejs?

**Comment by gengjiawen** [comment]
vs2017 build issue has been resolved.

**Comment by targos** [comment]
CI: https://ci.nodejs.org/view/MyJobs/job/node-test-commit-node-v8/450/

**Comment by gengjiawen** [comment]
With With https://github.com/nodejs/node-v8/pull/147 and https://github.com/nodejs/node-v8/issues/120 fixed, hopefully we have only two test case failed.

**Comment by liudonghua123** [comment]
Glad to here that, I hope I can use v8 8.0 as soon as possible. :haha:

**Comment by mmarchini** [comment]
#120 was not fixed upstream yet though :/

**Comment by gengjiawen** [comment]
> #120 was not fixed upstream yet though :/

got it wrong, should be https://github.com/nodejs/node-v8/issues/140

**Comment by MKRhere** [comment]
#140 is closed, should it be checked off?

**Comment by gengjiawen** [comment]
V8 8.1 landed on Node.js master.

**Comment by mmarchini** [comment]
Yes, this can be closed now. Hooray!
